version: '3'

services:
  logstash-01:
    image: docker.elastic.co/logstash/logstash:8.4.3
    volumes:
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./pipeline:/usr/share/logstash/pipeline:ro,Z
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
    networks:
      - techmaster
networks:
  techmaster:
    external: true