version: '3'

services:
  logstash:
    image: docker.elastic.co/logstash/logstash:8.4.3
    volumes:
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./pipeline:/usr/share/logstash/pipeline:ro,Z
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
    ports:
      - "5044:5044"
      - "50000:50000/tcp"
      - "50000:50000/udp"
      - "9600:9600"