version: "3"
services:
  elasticsearch:
    container_name: techmaster-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.2
    environment:
      - xpack.security.enabled=false  # security is disabled
      - discovery.type=single-node # single node
    mem_limit: 1073741824 # container memory limit 1G
    ports:
      - 9200:9200
    volumes:
      - data-elasticsearch:/usr/share/elasticsearch/data # mount data volume
    networks:
      - techmaster
volumes:
  data-elasticsearch:
    driver: local
networks:
  techmaster:
    external: true