filebeat.inputs:
- type: log
  paths: 
    - '/var/log/nginx/host.access.log'

output.elasticsearch:
<<<<<<< HEAD
  hosts: ["techmaster-elasticsearch:9200"]
=======
  hosts: ["elasticsearch:9200"]
>>>>>>> a51e0919fce03d08581bd4dfeceefaf256fd071d
  indices:
  - index: "trucntt3_nginx-%{[agent.version]}-%{+yyyy.MM.dd}"
