filebeat.inputs:
- type: log
  paths: 
    - '/var/log/nginx/host.access.log'

output.elasticsearch:
  hosts: ["techmaster-elasticsearch:9200"]
  indices:
  - index: "trucntt3_nginx-%{[agent.version]}-%{+yyyy.MM.dd}"
