version: "3.8"

services:
  filebeat-module:
    image: docker.elastic.co/beats/filebeat:8.4.2
    container_name: filebeat-module
    user: root
    volumes:
    - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
    - ./nginx.yml:/usr/share/filebeat/modules.d/nginx.yml
    - /home/ubuntu/ELK-tech-master/Lesson-2/nginx/log:/var/log/nginx/