version: "3.8"

services:
  filebeat-logstash-03:
    image: docker.elastic.co/beats/filebeat:8.4.2
    user: root
    volumes:
    - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
    - ../../../../Lesson-2/nginx/log:/var/log/nginx/
    networks:
      - techmaster
networks:
  techmaster:
    external: true