version: "3.8"

services:
  filebeat-base:
    image: docker.elastic.co/beats/filebeat:8.4.2
    container_name: filebeat-base
    user: root
    volumes:
    - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
    - ./test.log:/var/log/test.log
    networks:
      - techmaster
networks:
  techmaster:
    external: true