filebeat.inputs:
- type: log
  paths: 
    - '/var/log/test.log'

output.elasticsearch:
<<<<<<< HEAD
  hosts: ["192.168.58.131:9200"]
=======
  hosts: ["elasticsearch:9200"]
>>>>>>> a51e0919fce03d08581bd4dfeceefaf256fd071d
  indices:
    - index: "filebeat-base-%{[agent.version]}-%{+yyyy.MM.dd}"
