version: '3.1'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.4.2
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://18.140.233.111:9200
    ports:
      - 5601:5601
    volumes:
      - kibanadata:/usr/share/kibana/data
volumes:
  kibanadata: